// Auto-generated by scripts/build-data.mjs — do not edit manually
// Last generated: 2026-02-02T14:56:03.857Z

export interface TaskResult {
  id: string;
  occupation: string;
  sector: string;
  difficulty: string;
  estimatedHours: number;
  scores: Record<string, number>;
}

export interface OccupationSummary {
  occupation: string;
  sector: string;
  taskCount: number;
  scores: Record<string, number>;
  bestModel: string | null;
}

export interface EvaluationData {
  models: string[];
  modelLabels: Record<string, string>;
  tasks: TaskResult[];
  occupations: OccupationSummary[];
  universalFailures: TaskResult[];
  aggregateScores: Record<string, number>;
  totalTasks: number;
  fullTaskCount: number;
  oraclePassRate: number;
}

export const evaluationData: EvaluationData = {
  "models": [
    "gpt-oss-120b",
    "gpt-5.2",
    "gemini-3-pro-preview",
    "claude-sonnet-4.5"
  ],
  "modelLabels": {
    "gpt-oss-120b": "GPT-OSS 120B",
    "gpt-5.2": "GPT-5.2 Thinking",
    "gemini-3-pro-preview": "Gemini 3 Pro",
    "claude-sonnet-4.5": "Claude Sonnet 4.5"
  },
  "tasks": [
    {
      "id": "409a-valuation-v2",
      "occupation": "Financial and Investment Analysts",
      "sector": "Finance and Insurance",
      "difficulty": "hard",
      "estimatedHours": 7,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      }
    },
    {
      "id": "bill-of-quantities-quote",
      "occupation": "Project Management Specialists",
      "sector": "Professional, Scientific, and Technical Services",
      "difficulty": "hard",
      "estimatedHours": 7,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      }
    },
    {
      "id": "calculation-and-validation-of-billet-dimensions-for-single-channel-profile-pressing",
      "occupation": "Mechanical Engineers",
      "sector": "Manufacturing",
      "difficulty": "hard",
      "estimatedHours": 0.3,
      "scores": {
        "gpt-oss-120b": 0.33,
        "gpt-5.2": 0.33,
        "gemini-3-pro-preview": 0.67,
        "claude-sonnet-4.5": 0.33
      }
    },
    {
      "id": "data-center-exodus",
      "occupation": "Project Management Specialists",
      "sector": "Professional, Scientific, and Technical Services",
      "difficulty": "hard",
      "estimatedHours": 0.2,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      }
    },
    {
      "id": "dog-adoption-ad",
      "occupation": "Film & Video Editors",
      "sector": "Information",
      "difficulty": "medium",
      "estimatedHours": 0.2,
      "scores": {
        "gpt-oss-120b": 0.33,
        "gpt-5.2": 0.67,
        "gemini-3-pro-preview": 1,
        "claude-sonnet-4.5": 1
      }
    },
    {
      "id": "emr-migration",
      "occupation": "Project Management Specialists",
      "sector": "Professional, Scientific, and Technical Services",
      "difficulty": "hard",
      "estimatedHours": 7,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      }
    },
    {
      "id": "federal-procurement-dispute-resolution",
      "occupation": "Compliance Officers",
      "sector": "Wholesale Trade",
      "difficulty": "hard",
      "estimatedHours": 7,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      }
    },
    {
      "id": "film-promo-reel-editing",
      "occupation": "Film & Video Editors",
      "sector": "Information",
      "difficulty": "hard",
      "estimatedHours": 7,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0.67,
        "claude-sonnet-4.5": 0.33
      }
    },
    {
      "id": "financial-investment-portfolio-analysis",
      "occupation": "Financial and Investment Analysts",
      "sector": "Finance and Insurance",
      "difficulty": "hard",
      "estimatedHours": 0.1,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0.67,
        "gemini-3-pro-preview": 0.67,
        "claude-sonnet-4.5": 0.67
      }
    },
    {
      "id": "food-distribution-crisis",
      "occupation": "Order Clerks",
      "sector": "Wholesale Trade",
      "difficulty": "hard",
      "estimatedHours": 7,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      }
    },
    {
      "id": "forensic-merger-accounting-fraud",
      "occupation": "Accountants and Auditors",
      "sector": "Finance and Insurance",
      "difficulty": "hard",
      "estimatedHours": 0.2,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0.33
      }
    },
    {
      "id": "international-humanitarian-law-defenses-case-precedents-v2",
      "occupation": "Lawyers",
      "sector": "Professional, Scientific, and Technical Services",
      "difficulty": "hard",
      "estimatedHours": 7,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0.67,
        "gemini-3-pro-preview": 1,
        "claude-sonnet-4.5": 0.33
      }
    },
    {
      "id": "internet-shutdown-state-defense",
      "occupation": "Lawyers",
      "sector": "Professional, Scientific, and Technical Services",
      "difficulty": "hard",
      "estimatedHours": 7,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      }
    },
    {
      "id": "investment-analyst-screening",
      "occupation": "Financial and Investment Analysts",
      "sector": "Finance and Insurance",
      "difficulty": "hard",
      "estimatedHours": 0.1,
      "scores": {
        "gpt-oss-120b": 0.33,
        "gpt-5.2": 0.67,
        "gemini-3-pro-preview": 0.33,
        "claude-sonnet-4.5": 0.67
      }
    },
    {
      "id": "it-sustainability-initiative",
      "occupation": "Computer and Information Systems Managers",
      "sector": "Professional, Scientific, and Technical Services",
      "difficulty": "hard",
      "estimatedHours": 1,
      "scores": {
        "gpt-oss-120b": 0.33,
        "gpt-5.2": 1,
        "gemini-3-pro-preview": 1,
        "claude-sonnet-4.5": 0.67
      }
    },
    {
      "id": "maritime-arbitration-jurisdiction-of-tribunal-case-precedents-v2",
      "occupation": "Lawyers",
      "sector": "Professional, Scientific, and Technical Services",
      "difficulty": "hard",
      "estimatedHours": 7,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 1,
        "gemini-3-pro-preview": 1,
        "claude-sonnet-4.5": 0.33
      }
    },
    {
      "id": "order-clerk-complex",
      "occupation": "Order Clerks",
      "sector": "Wholesale Trade",
      "difficulty": "hard",
      "estimatedHours": 0.1,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 1,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 1
      }
    },
    {
      "id": "payroll-error-analysis",
      "occupation": "Accountants and Auditors",
      "sector": "Professional, Scientific, and Technical Services",
      "difficulty": "hard",
      "estimatedHours": 7,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      }
    },
    {
      "id": "pre-arbitral-deposit-international-arbitration",
      "occupation": "Lawyers",
      "sector": "Professional, Scientific, and Technical Services",
      "difficulty": "hard",
      "estimatedHours": 7,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      }
    },
    {
      "id": "real-estate-investment-analyzer",
      "occupation": "Financial and Investment Analysts",
      "sector": "Real Estate and Rental and Leasing",
      "difficulty": "hard",
      "estimatedHours": 7,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      }
    },
    {
      "id": "reliability-consultant-fintech",
      "occupation": "Software Developers",
      "sector": "Professional, Scientific, and Technical Services",
      "difficulty": "hard",
      "estimatedHours": 7,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      }
    },
    {
      "id": "screenplay-breakdown-storyboard",
      "occupation": "Producers & Directors",
      "sector": "Information",
      "difficulty": "hard",
      "estimatedHours": 7,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0.67,
        "gemini-3-pro-preview": 0.67,
        "claude-sonnet-4.5": 0.67
      }
    },
    {
      "id": "stripe-subscription-api",
      "occupation": "Software Developers",
      "sector": "Professional, Scientific, and Technical Services",
      "difficulty": "hard",
      "estimatedHours": 0.2,
      "scores": {
        "gpt-oss-120b": 0.33,
        "gpt-5.2": 1,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 1
      }
    },
    {
      "id": "tuneflow",
      "occupation": "Software Developers",
      "sector": "Professional, Scientific, and Technical Services",
      "difficulty": "hard",
      "estimatedHours": 0.2,
      "scores": {
        "gpt-oss-120b": 0.67,
        "gpt-5.2": 0.67,
        "gemini-3-pro-preview": 0.33,
        "claude-sonnet-4.5": 1
      }
    },
    {
      "id": "victoria-energy-correlation",
      "occupation": "Software Developers",
      "sector": "Professional, Scientific, and Technical Services",
      "difficulty": "hard",
      "estimatedHours": 7,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      }
    },
    {
      "id": "web-developer-booking",
      "occupation": "Software Developers",
      "sector": "Professional, Scientific, and Technical Services",
      "difficulty": "hard",
      "estimatedHours": 0.1,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      }
    }
  ],
  "occupations": [
    {
      "occupation": "Computer and Information Systems Managers",
      "sector": "Professional, Scientific, and Technical Services",
      "taskCount": 1,
      "scores": {
        "gpt-oss-120b": 0.33,
        "gpt-5.2": 1,
        "gemini-3-pro-preview": 1,
        "claude-sonnet-4.5": 0.67
      },
      "bestModel": "gpt-5.2"
    },
    {
      "occupation": "Producers & Directors",
      "sector": "Information",
      "taskCount": 1,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0.67,
        "gemini-3-pro-preview": 0.67,
        "claude-sonnet-4.5": 0.67
      },
      "bestModel": "gpt-5.2"
    },
    {
      "occupation": "Film & Video Editors",
      "sector": "Information",
      "taskCount": 2,
      "scores": {
        "gpt-oss-120b": 0.165,
        "gpt-5.2": 0.335,
        "gemini-3-pro-preview": 0.835,
        "claude-sonnet-4.5": 0.665
      },
      "bestModel": "gemini-3-pro-preview"
    },
    {
      "occupation": "Mechanical Engineers",
      "sector": "Manufacturing",
      "taskCount": 1,
      "scores": {
        "gpt-oss-120b": 0.33,
        "gpt-5.2": 0.33,
        "gemini-3-pro-preview": 0.67,
        "claude-sonnet-4.5": 0.33
      },
      "bestModel": "gemini-3-pro-preview"
    },
    {
      "occupation": "Lawyers",
      "sector": "Professional, Scientific, and Technical Services",
      "taskCount": 4,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0.4175,
        "gemini-3-pro-preview": 0.5,
        "claude-sonnet-4.5": 0.165
      },
      "bestModel": "gemini-3-pro-preview"
    },
    {
      "occupation": "Financial and Investment Analysts",
      "sector": "Finance and Insurance",
      "taskCount": 4,
      "scores": {
        "gpt-oss-120b": 0.0825,
        "gpt-5.2": 0.335,
        "gemini-3-pro-preview": 0.25,
        "claude-sonnet-4.5": 0.335
      },
      "bestModel": "gpt-5.2"
    },
    {
      "occupation": "Order Clerks",
      "sector": "Wholesale Trade",
      "taskCount": 2,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0.5,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0.5
      },
      "bestModel": "gpt-5.2"
    },
    {
      "occupation": "Software Developers",
      "sector": "Professional, Scientific, and Technical Services",
      "taskCount": 5,
      "scores": {
        "gpt-oss-120b": 0.2,
        "gpt-5.2": 0.334,
        "gemini-3-pro-preview": 0.066,
        "claude-sonnet-4.5": 0.4
      },
      "bestModel": "claude-sonnet-4.5"
    },
    {
      "occupation": "Accountants and Auditors",
      "sector": "Finance and Insurance",
      "taskCount": 2,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0.165
      },
      "bestModel": "claude-sonnet-4.5"
    },
    {
      "occupation": "Project Management Specialists",
      "sector": "Professional, Scientific, and Technical Services",
      "taskCount": 3,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      },
      "bestModel": null
    },
    {
      "occupation": "Compliance Officers",
      "sector": "Wholesale Trade",
      "taskCount": 1,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      },
      "bestModel": null
    }
  ],
  "universalFailures": [
    {
      "id": "409a-valuation-v2",
      "occupation": "Financial and Investment Analysts",
      "sector": "Finance and Insurance",
      "difficulty": "hard",
      "estimatedHours": 7,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      }
    },
    {
      "id": "bill-of-quantities-quote",
      "occupation": "Project Management Specialists",
      "sector": "Professional, Scientific, and Technical Services",
      "difficulty": "hard",
      "estimatedHours": 7,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      }
    },
    {
      "id": "data-center-exodus",
      "occupation": "Project Management Specialists",
      "sector": "Professional, Scientific, and Technical Services",
      "difficulty": "hard",
      "estimatedHours": 0.2,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      }
    },
    {
      "id": "emr-migration",
      "occupation": "Project Management Specialists",
      "sector": "Professional, Scientific, and Technical Services",
      "difficulty": "hard",
      "estimatedHours": 7,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      }
    },
    {
      "id": "federal-procurement-dispute-resolution",
      "occupation": "Compliance Officers",
      "sector": "Wholesale Trade",
      "difficulty": "hard",
      "estimatedHours": 7,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      }
    },
    {
      "id": "food-distribution-crisis",
      "occupation": "Order Clerks",
      "sector": "Wholesale Trade",
      "difficulty": "hard",
      "estimatedHours": 7,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      }
    },
    {
      "id": "internet-shutdown-state-defense",
      "occupation": "Lawyers",
      "sector": "Professional, Scientific, and Technical Services",
      "difficulty": "hard",
      "estimatedHours": 7,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      }
    },
    {
      "id": "payroll-error-analysis",
      "occupation": "Accountants and Auditors",
      "sector": "Professional, Scientific, and Technical Services",
      "difficulty": "hard",
      "estimatedHours": 7,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      }
    },
    {
      "id": "pre-arbitral-deposit-international-arbitration",
      "occupation": "Lawyers",
      "sector": "Professional, Scientific, and Technical Services",
      "difficulty": "hard",
      "estimatedHours": 7,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      }
    },
    {
      "id": "real-estate-investment-analyzer",
      "occupation": "Financial and Investment Analysts",
      "sector": "Real Estate and Rental and Leasing",
      "difficulty": "hard",
      "estimatedHours": 7,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      }
    },
    {
      "id": "reliability-consultant-fintech",
      "occupation": "Software Developers",
      "sector": "Professional, Scientific, and Technical Services",
      "difficulty": "hard",
      "estimatedHours": 7,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      }
    },
    {
      "id": "victoria-energy-correlation",
      "occupation": "Software Developers",
      "sector": "Professional, Scientific, and Technical Services",
      "difficulty": "hard",
      "estimatedHours": 7,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      }
    },
    {
      "id": "web-developer-booking",
      "occupation": "Software Developers",
      "sector": "Professional, Scientific, and Technical Services",
      "difficulty": "hard",
      "estimatedHours": 0.1,
      "scores": {
        "gpt-oss-120b": 0,
        "gpt-5.2": 0,
        "gemini-3-pro-preview": 0,
        "claude-sonnet-4.5": 0
      }
    }
  ],
  "aggregateScores": {
    "gpt-oss-120b": 0.0892,
    "gpt-5.2": 0.3212,
    "gemini-3-pro-preview": 0.2823,
    "claude-sonnet-4.5": 0.3204
  },
  "totalTasks": 26,
  "fullTaskCount": 217,
  "oraclePassRate": 0.8863
};
