// Auto-generated by scripts/build-gdpval-data.mjs - do not edit manually
// Last generated: 2026-02-02T17:51:02.921Z
// Source: https://huggingface.co/datasets/openai/gdpval

export interface GdpvalData {
  generatedAt: string;
  source: string;
  paperUrl: string;
  totalTasks: number;
  computed: {
    avgPromptWords: number;
    medianPromptWords: number;
    promptWordCountStats: { min: number; max: number; mean: number; median: number; p25: number; p75: number };
    promptWordCountBins: Array<{ range: string; count: number }>;
    avgReferenceFiles: number;
    medianReferenceFiles: number;
    referenceFileStats: { min: number; max: number; mean: number; median: number; p25: number; p75: number };
    percentTextOnly: number;
    uniqueOccupations: number;
    uniqueSectors: number;
    referenceFileTypes: string[];
    uniqueReferenceFileTypes: number;
    referenceFileTypeFrequency: Record<string, number>;
    sectorDistribution: Record<string, number>;
    occupationDistribution: Record<string, number>;
  };
  fromPaper: {
    avgDeliverableFiles: number;
    avgReferenceFilesReported: number;
    percentTextOnlyReported: number;
    medianCompletionHours: number;
    meanCompletionHours: number;
    meanDollarValue: number;
    qualityRating: number;
    difficultyRating: number;
    percentWellSpecified: number;
    evaluationMethod: string;
    humanAgreementRate: number;
    totalTasksFull: number;
  };
}

export const gdpvalData: GdpvalData = {
  "generatedAt": "2026-02-02T17:51:02.921Z",
  "source": "https://huggingface.co/datasets/openai/gdpval",
  "paperUrl": "https://arxiv.org/abs/2510.04374",
  "totalTasks": 220,
  "computed": {
    "avgPromptWords": 337.2,
    "medianPromptWords": 307,
    "promptWordCountStats": {
      "min": 100,
      "max": 1064,
      "mean": 337.2,
      "median": 307,
      "p25": 226,
      "p75": 419
    },
    "promptWordCountBins": [
      {
        "range": "0-200",
        "count": 37
      },
      {
        "range": "200-500",
        "count": 150
      },
      {
        "range": "500-800",
        "count": 29
      },
      {
        "range": "800-1200",
        "count": 4
      },
      {
        "range": "1200+",
        "count": 0
      }
    ],
    "avgReferenceFiles": 1.2,
    "medianReferenceFiles": 1,
    "referenceFileStats": {
      "min": 0,
      "max": 17,
      "mean": 1.2,
      "median": 1,
      "p25": 0,
      "p75": 2
    },
    "percentTextOnly": 44.5,
    "uniqueOccupations": 44,
    "uniqueSectors": 9,
    "referenceFileTypes": [
      "docx",
      "jpg",
      "mp3",
      "mp4",
      "pages",
      "pdf",
      "png",
      "pptx",
      "psd",
      "step",
      "txt",
      "wav",
      "xlsx",
      "zip"
    ],
    "uniqueReferenceFileTypes": 14,
    "referenceFileTypeFrequency": {
      "xlsx": 85,
      "pdf": 77,
      "txt": 1,
      "wav": 8,
      "mp3": 2,
      "docx": 66,
      "pages": 1,
      "psd": 1,
      "zip": 3,
      "mp4": 2,
      "png": 10,
      "step": 2,
      "pptx": 1,
      "jpg": 3
    },
    "sectorDistribution": {
      "Professional, Scientific, and Technical Services": 25,
      "Government": 25,
      "Information": 25,
      "Manufacturing": 25,
      "Real Estate and Rental and Leasing": 25,
      "Finance and Insurance": 25,
      "Wholesale Trade": 25,
      "Health Care and Social Assistance": 25,
      "Retail Trade": 20
    },
    "occupationDistribution": {
      "Accountants and Auditors": 5,
      "Administrative Services Managers": 5,
      "Audio and Video Technicians": 5,
      "Buyers and Purchasing Agents": 5,
      "Child, Family, and School Social Workers": 5,
      "Compliance Officers": 5,
      "Computer and Information Systems Managers": 5,
      "Concierges": 5,
      "Counter and Rental Clerks": 5,
      "Customer Service Representatives": 5,
      "Editors": 5,
      "Film and Video Editors": 5,
      "Financial and Investment Analysts": 5,
      "Financial Managers": 5,
      "First-Line Supervisors of Non-Retail Sales Workers": 5,
      "First-Line Supervisors of Office and Administrative Support Workers": 5,
      "First-Line Supervisors of Police and Detectives": 5,
      "First-Line Supervisors of Production and Operating Workers": 5,
      "First-Line Supervisors of Retail Sales Workers": 5,
      "General and Operations Managers": 5,
      "Industrial Engineers": 5,
      "Lawyers": 5,
      "Mechanical Engineers": 5,
      "Medical and Health Services Managers": 5,
      "Medical Secretaries and Administrative Assistants": 5,
      "News Analysts, Reporters, and Journalists": 5,
      "Nurse Practitioners": 5,
      "Order Clerks": 5,
      "Personal Financial Advisors": 5,
      "Private Detectives and Investigators": 5,
      "Producers and Directors": 5,
      "Project Management Specialists": 5,
      "Property, Real Estate, and Community Association Managers": 5,
      "Real Estate Brokers": 5,
      "Real Estate Sales Agents": 5,
      "Recreation Workers": 5,
      "Registered Nurses": 5,
      "Pharmacists": 5,
      "Sales Managers": 5,
      "Sales Representatives, Wholesale and Manufacturing, Except Technical and Scientific Products": 5,
      "Sales Representatives, Wholesale and Manufacturing, Technical and Scientific Products": 5,
      "Securities, Commodities, and Financial Services Sales Agents": 5,
      "Shipping, Receiving, and Inventory Clerks": 5,
      "Software Developers": 5
    }
  },
  "fromPaper": {
    "avgDeliverableFiles": 1.54,
    "avgReferenceFilesReported": 1.92,
    "percentTextOnlyReported": 32.3,
    "medianCompletionHours": 5,
    "meanCompletionHours": 9.49,
    "meanDollarValue": 398.46,
    "qualityRating": 4.47,
    "difficultyRating": 3.32,
    "percentWellSpecified": 89,
    "evaluationMethod": "Pairwise comparison (GPT-5 judge)",
    "humanAgreementRate": 0.66,
    "totalTasksFull": 1320
  }
};
